<?php

namespace Fo3nix\ShopifyGraphQL\ShopifyAdmin202507;

use GraphQL\SchemaObject\EnumObject;

class CollectionRuleColumnEnumObject extends EnumObject
{
    const TAG = "TAG";
    const TITLE = "TITLE";
    const TYPE = "TYPE";
    const PRODUCT_TAXONOMY_NODE_ID = "PRODUCT_TAXONOMY_NODE_ID";
    const PRODUCT_CATEGORY_ID = "PRODUCT_CATEGORY_ID";
    const PRODUCT_CATEGORY_ID_WITH_DESCENDANTS = "PRODUCT_CATEGORY_ID_WITH_DESCENDANTS";
    const VENDOR = "VENDOR";
    const VARIANT_PRICE = "VARIANT_PRICE";
    const IS_PRICE_REDUCED = "IS_PRICE_REDUCED";
    const VARIANT_COMPARE_AT_PRICE = "VARIANT_COMPARE_AT_PRICE";
    const VARIANT_WEIGHT = "VARIANT_WEIGHT";
    const VARIANT_INVENTORY = "VARIANT_INVENTORY";
    const VARIANT_TITLE = "VARIANT_TITLE";
    const PRODUCT_METAFIELD_DEFINITION = "PRODUCT_METAFIELD_DEFINITION";
    const VARIANT_METAFIELD_DEFINITION = "VARIANT_METAFIELD_DEFINITION";
}
