<?php

namespace Fo3nix\ShopifyGraphQL\ShopifyAdmin202507;

use GraphQL\SchemaObject\EnumObject;

class CustomerPaymentMethodRevocationReasonEnumObject extends EnumObject
{
    const AUTHORIZE_NET_GATEWAY_NOT_ENABLED = "AUTHORIZE_NET_GATEWAY_NOT_ENABLED";
    const AUTHORIZE_NET_RETURNED_NO_PAYMENT_METHOD = "AUTHORIZE_NET_RETURNED_NO_PAYMENT_METHOD";
    const FAILED_TO_UPDATE_CREDIT_CARD = "FAILED_TO_UPDATE_CREDIT_CARD";
    const STRIPE_API_AUTHENTICATION_ERROR = "STRIPE_API_AUTHENTICATION_ERROR";
    const STRIPE_API_INVALID_REQUEST_ERROR = "STRIPE_API_INVALID_REQUEST_ERROR";
    const STRIPE_GATEWAY_NOT_ENABLED = "STRIPE_GATEWAY_NOT_ENABLED";
    const STRIPE_RETURNED_NO_PAYMENT_METHOD = "STRIPE_RETURNED_NO_PAYMENT_METHOD";
    const STRIPE_PAYMENT_METHOD_NOT_CARD = "STRIPE_PAYMENT_METHOD_NOT_CARD";
    const BRAINTREE_API_AUTHENTICATION_ERROR = "BRAINTREE_API_AUTHENTICATION_ERROR";
    const BRAINTREE_GATEWAY_NOT_ENABLED = "BRAINTREE_GATEWAY_NOT_ENABLED";
    const BRAINTREE_RETURNED_NO_PAYMENT_METHOD = "BRAINTREE_RETURNED_NO_PAYMENT_METHOD";
    const BRAINTREE_PAYMENT_METHOD_NOT_CARD = "BRAINTREE_PAYMENT_METHOD_NOT_CARD";
    const PAYMENT_METHOD_VERIFICATION_FAILED = "PAYMENT_METHOD_VERIFICATION_FAILED";
    const THREE_D_SECURE_FLOW_IN_VERIFICATION_NOT_IMPLEMENTED = "THREE_D_SECURE_FLOW_IN_VERIFICATION_NOT_IMPLEMENTED";
    const MANUALLY_REVOKED = "MANUALLY_REVOKED";
    const FAILED_TO_RETRIEVE_BILLING_ADDRESS = "FAILED_TO_RETRIEVE_BILLING_ADDRESS";
    const MERGED = "MERGED";
    const CUSTOMER_REDACTED = "CUSTOMER_REDACTED";
    const TOO_MANY_CONSECUTIVE_FAILURES = "TOO_MANY_CONSECUTIVE_FAILURES";
    const CVV_ATTEMPTS_LIMIT_EXCEEDED = "CVV_ATTEMPTS_LIMIT_EXCEEDED";
}
