<?php

namespace Fo3nix\ShopifyGraphQL\ShopifyAdmin202507;

use GraphQL\SchemaObject\EnumObject;

class DiscountErrorCodeEnumObject extends EnumObject
{
    const BLANK = "BLANK";
    const PRESENT = "PRESENT";
    const EQUAL_TO = "EQUAL_TO";
    const GREATER_THAN = "GREATER_THAN";
    const GREATER_THAN_OR_EQUAL_TO = "GREATER_THAN_OR_EQUAL_TO";
    const INVALID = "INVALID";
    const LESS_THAN_OR_EQUAL_TO = "LESS_THAN_OR_EQUAL_TO";
    const LESS_THAN = "LESS_THAN";
    const TAKEN = "TAKEN";
    const TOO_LONG = "TOO_LONG";
    const TOO_SHORT = "TOO_SHORT";
    const INTERNAL_ERROR = "INTERNAL_ERROR";
    const TOO_MANY_ARGUMENTS = "TOO_MANY_ARGUMENTS";
    const MISSING_ARGUMENT = "MISSING_ARGUMENT";
    const ACTIVE_PERIOD_OVERLAP = "ACTIVE_PERIOD_OVERLAP";
    const END_DATE_BEFORE_START_DATE = "END_DATE_BEFORE_START_DATE";
    const EXCEEDED_MAX = "EXCEEDED_MAX";
    const MINIMUM_SUBTOTAL_AND_QUANTITY_RANGE_BOTH_PRESENT = "MINIMUM_SUBTOTAL_AND_QUANTITY_RANGE_BOTH_PRESENT";
    const VALUE_OUTSIDE_RANGE = "VALUE_OUTSIDE_RANGE";
    const CONFLICT = "CONFLICT";
    const IMPLICIT_DUPLICATE = "IMPLICIT_DUPLICATE";
    const DUPLICATE = "DUPLICATE";
    const INCLUSION = "INCLUSION";
    const INVALID_COMBINES_WITH_FOR_DISCOUNT_CLASS = "INVALID_COMBINES_WITH_FOR_DISCOUNT_CLASS";
    const INVALID_DISCOUNT_CLASS_FOR_PRICE_RULE = "INVALID_DISCOUNT_CLASS_FOR_PRICE_RULE";
    const MAX_APP_DISCOUNTS = "MAX_APP_DISCOUNTS";
    const APPLIES_ON_NOTHING = "APPLIES_ON_NOTHING";
    const RECURRING_CYCLE_LIMIT_NOT_A_VALID_INTEGER = "RECURRING_CYCLE_LIMIT_NOT_A_VALID_INTEGER";
    const MULTIPLE_RECURRING_CYCLE_LIMIT_FOR_NON_SUBSCRIPTION_ITEMS = "MULTIPLE_RECURRING_CYCLE_LIMIT_FOR_NON_SUBSCRIPTION_ITEMS";
}
