<?php

namespace Fo3nix\ShopifyGraphQL\ShopifyAdmin202507;

use GraphQL\SchemaObject\EnumObject;

class LocalizationExtensionKeyEnumObject extends EnumObject
{
    const TAX_CREDENTIAL_BR = "TAX_CREDENTIAL_BR";
    const SHIPPING_CREDENTIAL_BR = "SHIPPING_CREDENTIAL_BR";
    const TAX_CREDENTIAL_CL = "TAX_CREDENTIAL_CL";
    const SHIPPING_CREDENTIAL_CL = "SHIPPING_CREDENTIAL_CL";
    const SHIPPING_CREDENTIAL_CN = "SHIPPING_CREDENTIAL_CN";
    const TAX_CREDENTIAL_CO = "TAX_CREDENTIAL_CO";
    const TAX_CREDENTIAL_TYPE_CO = "TAX_CREDENTIAL_TYPE_CO";
    const SHIPPING_CREDENTIAL_CO = "SHIPPING_CREDENTIAL_CO";
    const SHIPPING_CREDENTIAL_TYPE_CO = "SHIPPING_CREDENTIAL_TYPE_CO";
    const TAX_CREDENTIAL_CR = "TAX_CREDENTIAL_CR";
    const SHIPPING_CREDENTIAL_CR = "SHIPPING_CREDENTIAL_CR";
    const TAX_CREDENTIAL_EC = "TAX_CREDENTIAL_EC";
    const SHIPPING_CREDENTIAL_EC = "SHIPPING_CREDENTIAL_EC";
    const TAX_CREDENTIAL_GT = "TAX_CREDENTIAL_GT";
    const SHIPPING_CREDENTIAL_GT = "SHIPPING_CREDENTIAL_GT";
    const TAX_CREDENTIAL_ID = "TAX_CREDENTIAL_ID";
    const SHIPPING_CREDENTIAL_ID = "SHIPPING_CREDENTIAL_ID";
    const TAX_CREDENTIAL_IT = "TAX_CREDENTIAL_IT";
    const TAX_EMAIL_IT = "TAX_EMAIL_IT";
    const TAX_CREDENTIAL_MY = "TAX_CREDENTIAL_MY";
    const SHIPPING_CREDENTIAL_MY = "SHIPPING_CREDENTIAL_MY";
    const SHIPPING_CREDENTIAL_MX = "SHIPPING_CREDENTIAL_MX";
    const TAX_CREDENTIAL_MX = "TAX_CREDENTIAL_MX";
    const TAX_CREDENTIAL_TYPE_MX = "TAX_CREDENTIAL_TYPE_MX";
    const TAX_CREDENTIAL_USE_MX = "TAX_CREDENTIAL_USE_MX";
    const TAX_CREDENTIAL_PY = "TAX_CREDENTIAL_PY";
    const SHIPPING_CREDENTIAL_PY = "SHIPPING_CREDENTIAL_PY";
    const TAX_CREDENTIAL_PE = "TAX_CREDENTIAL_PE";
    const SHIPPING_CREDENTIAL_PE = "SHIPPING_CREDENTIAL_PE";
    const TAX_CREDENTIAL_PT = "TAX_CREDENTIAL_PT";
    const SHIPPING_CREDENTIAL_PT = "SHIPPING_CREDENTIAL_PT";
    const SHIPPING_CREDENTIAL_KR = "SHIPPING_CREDENTIAL_KR";
    const TAX_CREDENTIAL_ES = "TAX_CREDENTIAL_ES";
    const SHIPPING_CREDENTIAL_ES = "SHIPPING_CREDENTIAL_ES";
    const SHIPPING_CREDENTIAL_TW = "SHIPPING_CREDENTIAL_TW";
    const TAX_CREDENTIAL_TR = "TAX_CREDENTIAL_TR";
    const SHIPPING_CREDENTIAL_TR = "SHIPPING_CREDENTIAL_TR";
}
