<?php

namespace Fo3nix\ShopifyGraphQL\ShopifyAdmin202507;

use GraphQL\SchemaObject\EnumObject;

class MediaErrorCodeEnumObject extends EnumObject
{
    const UNKNOWN = "UNKNOWN";
    const INVALID_SIGNED_URL = "INVALID_SIGNED_URL";
    const IMAGE_DOWNLOAD_FAILURE = "IMAGE_DOWNLOAD_FAILURE";
    const IMAGE_PROCESSING_FAILURE = "IMAGE_PROCESSING_FAILURE";
    const MEDIA_TIMEOUT_ERROR = "MEDIA_TIMEOUT_ERROR";
    const EXTERNAL_VIDEO_NOT_FOUND = "EXTERNAL_VIDEO_NOT_FOUND";
    const EXTERNAL_VIDEO_UNLISTED = "EXTERNAL_VIDEO_UNLISTED";
    const EXTERNAL_VIDEO_INVALID_ASPECT_RATIO = "EXTERNAL_VIDEO_INVALID_ASPECT_RATIO";
    const EXTERNAL_VIDEO_EMBED_DISABLED = "EXTERNAL_VIDEO_EMBED_DISABLED";
    const EXTERNAL_VIDEO_EMBED_NOT_FOUND_OR_TRANSCODING = "EXTERNAL_VIDEO_EMBED_NOT_FOUND_OR_TRANSCODING";
    const GENERIC_FILE_DOWNLOAD_FAILURE = "GENERIC_FILE_DOWNLOAD_FAILURE";
    const GENERIC_FILE_INVALID_SIZE = "GENERIC_FILE_INVALID_SIZE";
    const VIDEO_METADATA_READ_ERROR = "VIDEO_METADATA_READ_ERROR";
    const VIDEO_INVALID_FILETYPE_ERROR = "VIDEO_INVALID_FILETYPE_ERROR";
    const VIDEO_MIN_WIDTH_ERROR = "VIDEO_MIN_WIDTH_ERROR";
    const VIDEO_MAX_WIDTH_ERROR = "VIDEO_MAX_WIDTH_ERROR";
    const VIDEO_MIN_HEIGHT_ERROR = "VIDEO_MIN_HEIGHT_ERROR";
    const VIDEO_MAX_HEIGHT_ERROR = "VIDEO_MAX_HEIGHT_ERROR";
    const VIDEO_MIN_DURATION_ERROR = "VIDEO_MIN_DURATION_ERROR";
    const VIDEO_MAX_DURATION_ERROR = "VIDEO_MAX_DURATION_ERROR";
    const VIDEO_VALIDATION_ERROR = "VIDEO_VALIDATION_ERROR";
    const MODEL3D_VALIDATION_ERROR = "MODEL3D_VALIDATION_ERROR";
    const MODEL3D_THUMBNAIL_GENERATION_ERROR = "MODEL3D_THUMBNAIL_GENERATION_ERROR";
    const MODEL3D_THUMBNAIL_REGENERATION_ERROR = "MODEL3D_THUMBNAIL_REGENERATION_ERROR";
    const MODEL3D_GLB_TO_USDZ_CONVERSION_ERROR = "MODEL3D_GLB_TO_USDZ_CONVERSION_ERROR";
    const MODEL3D_GLB_OUTPUT_CREATION_ERROR = "MODEL3D_GLB_OUTPUT_CREATION_ERROR";
    const MODEL3D_PROCESSING_FAILURE = "MODEL3D_PROCESSING_FAILURE";
    const UNSUPPORTED_IMAGE_FILE_TYPE = "UNSUPPORTED_IMAGE_FILE_TYPE";
    const INVALID_IMAGE_FILE_SIZE = "INVALID_IMAGE_FILE_SIZE";
    const INVALID_IMAGE_ASPECT_RATIO = "INVALID_IMAGE_ASPECT_RATIO";
    const INVALID_IMAGE_RESOLUTION = "INVALID_IMAGE_RESOLUTION";
    const FILE_STORAGE_LIMIT_EXCEEDED = "FILE_STORAGE_LIMIT_EXCEEDED";
    const DUPLICATE_FILENAME_ERROR = "DUPLICATE_FILENAME_ERROR";
}
