<?php

namespace Fo3nix\ShopifyGraphQL\ShopifyAdmin202507;

use GraphQL\SchemaObject\EnumObject;

class ShopPayPaymentRequestReceiptProcessingStatusErrorCodeEnumObject extends EnumObject
{
    const INCORRECT_NUMBER = "INCORRECT_NUMBER";
    const INVALID_NUMBER = "INVALID_NUMBER";
    const INVALID_EXPIRY_DATE = "INVALID_EXPIRY_DATE";
    const INVALID_CVC = "INVALID_CVC";
    const EXPIRED_CARD = "EXPIRED_CARD";
    const INCORRECT_CVC = "INCORRECT_CVC";
    const INCORRECT_ZIP = "INCORRECT_ZIP";
    const INCORRECT_ADDRESS = "INCORRECT_ADDRESS";
    const INCORRECT_PIN = "INCORRECT_PIN";
    const AMOUNT_TOO_SMALL = "AMOUNT_TOO_SMALL";
    const CARD_DECLINED = "CARD_DECLINED";
    const PROCESSING_ERROR = "PROCESSING_ERROR";
    const CALL_ISSUER = "CALL_ISSUER";
    const THREE_D_SECURE_FAILED = "THREE_D_SECURE_FAILED";
    const FRAUD_SUSPECTED = "FRAUD_SUSPECTED";
    const PICK_UP_CARD = "PICK_UP_CARD";
    const CONFIG_ERROR = "CONFIG_ERROR";
    const TEST_MODE_LIVE_CARD = "TEST_MODE_LIVE_CARD";
    const UNSUPPORTED_FEATURE = "UNSUPPORTED_FEATURE";
    const GENERIC_ERROR = "GENERIC_ERROR";
    const INVALID_COUNTRY = "INVALID_COUNTRY";
    const INVALID_AMOUNT = "INVALID_AMOUNT";
    const PAYMENT_METHOD_UNAVAILABLE = "PAYMENT_METHOD_UNAVAILABLE";
}
