<?php

namespace Fo3nix\ShopifyGraphQL\ShopifyAdmin202507;

use GraphQL\SchemaObject\EnumObject;

class ShopifyPaymentsBusinessTypeEnumObject extends EnumObject
{
    const CORPORATION = "CORPORATION";
    const GOVERNMENT = "GOVERNMENT";
    const INCORPORATED_PARTNERSHIP = "INCORPORATED_PARTNERSHIP";
    const INDIVIDUAL = "INDIVIDUAL";
    const LLC = "LLC";
    const NON_PROFIT = "NON_PROFIT";
    const NON_PROFIT_INCORPORATED = "NON_PROFIT_INCORPORATED";
    const NON_PROFIT_UNINCORPORATED = "NON_PROFIT_UNINCORPORATED";
    const NON_PROFIT_UNINCORPORATED_ASSOCIATION = "NON_PROFIT_UNINCORPORATED_ASSOCIATION";
    const NON_PROFIT_REGISTERED_CHARITY = "NON_PROFIT_REGISTERED_CHARITY";
    const PARTNERSHIP = "PARTNERSHIP";
    const PRIVATE_CORPORATION = "PRIVATE_CORPORATION";
    const PUBLIC_COMPANY = "PUBLIC_COMPANY";
    const PUBLIC_CORPORATION = "PUBLIC_CORPORATION";
    const SOLE_PROP = "SOLE_PROP";
    const UNINCORPORATED_PARTNERSHIP = "UNINCORPORATED_PARTNERSHIP";
    const PRIVATE_MULTI_MEMBER_LLC = "PRIVATE_MULTI_MEMBER_LLC";
    const PRIVATE_SINGLE_MEMBER_LLC = "PRIVATE_SINGLE_MEMBER_LLC";
    const PRIVATE_UNINCORPORATED_ASSOCIATION = "PRIVATE_UNINCORPORATED_ASSOCIATION";
    const PRIVATE_PARTNERSHIP = "PRIVATE_PARTNERSHIP";
    const PUBLIC_PARTNERSHIP = "PUBLIC_PARTNERSHIP";
    const FREE_ZONE_ESTABLISHMENT = "FREE_ZONE_ESTABLISHMENT";
    const FREE_ZONE_LLC = "FREE_ZONE_LLC";
    const SOLE_ESTABLISHMENT = "SOLE_ESTABLISHMENT";
    const NOT_SET = "NOT_SET";
}
