<?php

namespace Fo3nix\ShopifyGraphQL\ShopifyAdmin202507;

use GraphQL\SchemaObject\EnumObject;

class ShopifyPaymentsDisputeReasonEnumObject extends EnumObject
{
    const FRAUDULENT = "FRAUDULENT";
    const GENERAL = "GENERAL";
    const UNRECOGNIZED = "UNRECOGNIZED";
    const DUPLICATE = "DUPLICATE";
    const SUBSCRIPTION_CANCELLED = "SUBSCRIPTION_CANCELLED";
    const PRODUCT_UNACCEPTABLE = "PRODUCT_UNACCEPTABLE";
    const PRODUCT_NOT_RECEIVED = "PRODUCT_NOT_RECEIVED";
    const CREDIT_NOT_PROCESSED = "CREDIT_NOT_PROCESSED";
    const INCORRECT_ACCOUNT_DETAILS = "INCORRECT_ACCOUNT_DETAILS";
    const INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS";
    const BANK_CANNOT_PROCESS = "BANK_CANNOT_PROCESS";
    const DEBIT_NOT_AUTHORIZED = "DEBIT_NOT_AUTHORIZED";
    const CUSTOMER_INITIATED = "CUSTOMER_INITIATED";
    const NONCOMPLIANT = "NONCOMPLIANT";
}
