<?php

namespace Fo3nix\ShopifyGraphQL\ShopifyAdmin202507;

use GraphQL\SchemaObject\EnumObject;

class StaffMemberPermissionEnumObject extends EnumObject
{
    const APPLICATIONS = "APPLICATIONS";
    const CHANNELS = "CHANNELS";
    const CREATE_AND_EDIT_CUSTOMERS = "CREATE_AND_EDIT_CUSTOMERS";
    const CREATE_AND_EDIT_GIFT_CARDS = "CREATE_AND_EDIT_GIFT_CARDS";
    const CUSTOMERS = "CUSTOMERS";
    const DASHBOARD = "DASHBOARD";
    const DEACTIVATE_GIFT_CARDS = "DEACTIVATE_GIFT_CARDS";
    const DELETE_CUSTOMERS = "DELETE_CUSTOMERS";
    const DOMAINS = "DOMAINS";
    const DRAFT_ORDERS = "DRAFT_ORDERS";
    const EDIT_ORDERS = "EDIT_ORDERS";
    const ERASE_CUSTOMER_DATA = "ERASE_CUSTOMER_DATA";
    const EXPORT_CUSTOMERS = "EXPORT_CUSTOMERS";
    const EXPORT_GIFT_CARDS = "EXPORT_GIFT_CARDS";
    const GIFT_CARDS = "GIFT_CARDS";
    const LINKS = "LINKS";
    const LOCATIONS = "LOCATIONS";
    const VIEW_MARKETS = "VIEW_MARKETS";
    const CREATE_AND_EDIT_MARKETS = "CREATE_AND_EDIT_MARKETS";
    const DELETE_MARKETS = "DELETE_MARKETS";
    const MARKETING = "MARKETING";
    const MARKETING_SECTION = "MARKETING_SECTION";
    const MERGE_CUSTOMERS = "MERGE_CUSTOMERS";
    const ORDERS = "ORDERS";
    const OVERVIEWS = "OVERVIEWS";
    const PAGES = "PAGES";
    const PAY_ORDERS_BY_VAULTED_CARD = "PAY_ORDERS_BY_VAULTED_CARD";
    const PREFERENCES = "PREFERENCES";
    const PRODUCTS = "PRODUCTS";
    const REPORTS = "REPORTS";
    const REQUEST_CUSTOMER_DATA = "REQUEST_CUSTOMER_DATA";
    const THEMES = "THEMES";
}
