<?php

namespace Fo3nix\ShopifyGraphQL\ShopifyAdmin202507;

use GraphQL\SchemaObject\EnumObject;

class SubscriptionDiscountRejectionReasonEnumObject extends EnumObject
{
    const NOT_FOUND = "NOT_FOUND";
    const NO_ENTITLED_LINE_ITEMS = "NO_ENTITLED_LINE_ITEMS";
    const QUANTITY_NOT_IN_RANGE = "QUANTITY_NOT_IN_RANGE";
    const PURCHASE_NOT_IN_RANGE = "PURCHASE_NOT_IN_RANGE";
    const CUSTOMER_NOT_ELIGIBLE = "CUSTOMER_NOT_ELIGIBLE";
    const USAGE_LIMIT_REACHED = "USAGE_LIMIT_REACHED";
    const CUSTOMER_USAGE_LIMIT_REACHED = "CUSTOMER_USAGE_LIMIT_REACHED";
    const CURRENTLY_INACTIVE = "CURRENTLY_INACTIVE";
    const NO_ENTITLED_SHIPPING_LINES = "NO_ENTITLED_SHIPPING_LINES";
    const INCOMPATIBLE_PURCHASE_TYPE = "INCOMPATIBLE_PURCHASE_TYPE";
    const INTERNAL_ERROR = "INTERNAL_ERROR";
}
