<?php

namespace Fo3nix\ShopifyGraphQL\ShopifyAdmin202507;

use GraphQL\SchemaObject\EnumObject;

class SubscriptionBillingAttemptErrorCodeEnumObject extends EnumObject
{
    const PAYMENT_METHOD_NOT_FOUND = "PAYMENT_METHOD_NOT_FOUND";
    const PAYMENT_PROVIDER_IS_NOT_ENABLED = "PAYMENT_PROVIDER_IS_NOT_ENABLED";
    const INVALID_PAYMENT_METHOD = "INVALID_PAYMENT_METHOD";
    const UNEXPECTED_ERROR = "UNEXPECTED_ERROR";
    const EXPIRED_PAYMENT_METHOD = "EXPIRED_PAYMENT_METHOD";
    const PAYMENT_METHOD_DECLINED = "PAYMENT_METHOD_DECLINED";
    const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
    const TEST_MODE = "TEST_MODE";
    const BUYER_CANCELED_PAYMENT_METHOD = "BUYER_CANCELED_PAYMENT_METHOD";
    const CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND";
    const CUSTOMER_INVALID = "CUSTOMER_INVALID";
    const INVALID_SHIPPING_ADDRESS = "INVALID_SHIPPING_ADDRESS";
    const INVALID_CUSTOMER_BILLING_AGREEMENT = "INVALID_CUSTOMER_BILLING_AGREEMENT";
    const INVOICE_ALREADY_PAID = "INVOICE_ALREADY_PAID";
    const PAYMENT_METHOD_INCOMPATIBLE_WITH_GATEWAY_CONFIG = "PAYMENT_METHOD_INCOMPATIBLE_WITH_GATEWAY_CONFIG";
    const AMOUNT_TOO_SMALL = "AMOUNT_TOO_SMALL";
    const INVENTORY_ALLOCATIONS_NOT_FOUND = "INVENTORY_ALLOCATIONS_NOT_FOUND";
    const INSUFFICIENT_INVENTORY = "INSUFFICIENT_INVENTORY";
    const TRANSIENT_ERROR = "TRANSIENT_ERROR";
    const INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS";
    const PURCHASE_TYPE_NOT_SUPPORTED = "PURCHASE_TYPE_NOT_SUPPORTED";
    const PAYPAL_ERROR_GENERAL = "PAYPAL_ERROR_GENERAL";
    const CARD_NUMBER_INCORRECT = "CARD_NUMBER_INCORRECT";
    const FRAUD_SUSPECTED = "FRAUD_SUSPECTED";
    const NON_TEST_ORDER_LIMIT_REACHED = "NON_TEST_ORDER_LIMIT_REACHED";
    const FREE_GIFT_CARD_NOT_ALLOWED = "FREE_GIFT_CARD_NOT_ALLOWED";
}
