<?php

namespace Fo3nix\ShopifyGraphQL\ShopifyAdmin202507;

use GraphQL\SchemaObject\EnumObject;

class TranslatableResourceTypeEnumObject extends EnumObject
{
    const ARTICLE = "ARTICLE";
    const BLOG = "BLOG";
    const COLLECTION = "COLLECTION";
    const DELIVERY_METHOD_DEFINITION = "DELIVERY_METHOD_DEFINITION";
    const EMAIL_TEMPLATE = "EMAIL_TEMPLATE";
    const FILTER = "FILTER";
    const LINK = "LINK";
    const MENU = "MENU";
    const METAFIELD = "METAFIELD";
    const METAOBJECT = "METAOBJECT";
    const ONLINE_STORE_THEME = "ONLINE_STORE_THEME";
    const ONLINE_STORE_THEME_APP_EMBED = "ONLINE_STORE_THEME_APP_EMBED";
    const ONLINE_STORE_THEME_JSON_TEMPLATE = "ONLINE_STORE_THEME_JSON_TEMPLATE";
    const ONLINE_STORE_THEME_LOCALE_CONTENT = "ONLINE_STORE_THEME_LOCALE_CONTENT";
    const ONLINE_STORE_THEME_SECTION_GROUP = "ONLINE_STORE_THEME_SECTION_GROUP";
    const ONLINE_STORE_THEME_SETTINGS_CATEGORY = "ONLINE_STORE_THEME_SETTINGS_CATEGORY";
    const ONLINE_STORE_THEME_SETTINGS_DATA_SECTIONS = "ONLINE_STORE_THEME_SETTINGS_DATA_SECTIONS";
    const PACKING_SLIP_TEMPLATE = "PACKING_SLIP_TEMPLATE";
    const PAGE = "PAGE";
    const PAYMENT_GATEWAY = "PAYMENT_GATEWAY";
    const PRODUCT = "PRODUCT";
    const PRODUCT_OPTION = "PRODUCT_OPTION";
    const PRODUCT_OPTION_VALUE = "PRODUCT_OPTION_VALUE";
    const SELLING_PLAN = "SELLING_PLAN";
    const SELLING_PLAN_GROUP = "SELLING_PLAN_GROUP";
    const SHOP = "SHOP";
    const SHOP_POLICY = "SHOP_POLICY";
}
