<?php

namespace Fo3nix\ShopifyGraphQL\ShopifyAdmin202604;

use GraphQL\SchemaObject\ArgumentsObject;

class ShopifyCheckoutAndAccountsConfigurationBrandingCustomerAccountsComponentsMainArgumentsObject extends ArgumentsObject
{}
