<?php

namespace Fo3nix\ShopifyGraphQL\ShopifyAdmin202604;

use GraphQL\SchemaObject\EnumObject;

class ShopifySubscriptionBillingAttemptGeneralErrorCodeEnumObject extends EnumObject
{
    const NON_TEST_ORDER_LIMIT_REACHED = "NON_TEST_ORDER_LIMIT_REACHED";
    const FREE_GIFT_CARD_NOT_ALLOWED = "FREE_GIFT_CARD_NOT_ALLOWED";
    const CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND";
    const CUSTOMER_INVALID = "CUSTOMER_INVALID";
    const INVALID_BILLING_ADDRESS = "INVALID_BILLING_ADDRESS";
    const MERCHANT_ACCOUNT_ERROR = "MERCHANT_ACCOUNT_ERROR";
    const PAYMENT_METHOD_NOT_FOUND = "PAYMENT_METHOD_NOT_FOUND";
    const PAYMENT_METHOD_NOT_SPECIFIED = "PAYMENT_METHOD_NOT_SPECIFIED";
    const PAYMENT_METHOD_INCOMPATIBLE_WITH_GATEWAY_CONFIG = "PAYMENT_METHOD_INCOMPATIBLE_WITH_GATEWAY_CONFIG";
    const PAYMENT_PROVIDER_IS_NOT_ENABLED = "PAYMENT_PROVIDER_IS_NOT_ENABLED";
}
