<?php

namespace Fo3nix\ShopifyGraphQL\ShopifyAdmin202610;

use GraphQL\SchemaObject\ArgumentsObject;

class ShopifySubscriptionContractCalculationProjectedOrderTotalsTotalDeliveryDiscountsArgumentsObject extends ArgumentsObject
{}
