<?php

namespace Fo3nix\ShopifyGraphQL\ShopifyAdmin202610;

use GraphQL\SchemaObject\EnumObject;

class ShopifySubscriptionBillingAttemptErrorCodeEnumObject extends EnumObject
{
    const PAYMENT_METHOD_NOT_FOUND = "PAYMENT_METHOD_NOT_FOUND";
    const PAYMENT_PROVIDER_IS_NOT_ENABLED = "PAYMENT_PROVIDER_IS_NOT_ENABLED";
    const INVALID_PAYMENT_METHOD = "INVALID_PAYMENT_METHOD";
    const UNEXPECTED_ERROR = "UNEXPECTED_ERROR";
    const EXPIRED_PAYMENT_METHOD = "EXPIRED_PAYMENT_METHOD";
    const PAYMENT_METHOD_DECLINED = "PAYMENT_METHOD_DECLINED";
    const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
    const TEST_MODE = "TEST_MODE";
    const BUYER_CANCELED_PAYMENT_METHOD = "BUYER_CANCELED_PAYMENT_METHOD";
    const CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND";
    const CUSTOMER_INVALID = "CUSTOMER_INVALID";
    const INVALID_SHIPPING_ADDRESS = "INVALID_SHIPPING_ADDRESS";
    const INVALID_CUSTOMER_BILLING_AGREEMENT = "INVALID_CUSTOMER_BILLING_AGREEMENT";
    const INVOICE_ALREADY_PAID = "INVOICE_ALREADY_PAID";
    const PAYMENT_METHOD_INCOMPATIBLE_WITH_GATEWAY_CONFIG = "PAYMENT_METHOD_INCOMPATIBLE_WITH_GATEWAY_CONFIG";
    const AMOUNT_TOO_SMALL = "AMOUNT_TOO_SMALL";
    const AMOUNT_TOO_LARGE = "AMOUNT_TOO_LARGE";
    const MERCHANT_ACCOUNT_ERROR = "MERCHANT_ACCOUNT_ERROR";
    const INVENTORY_ALLOCATIONS_NOT_FOUND = "INVENTORY_ALLOCATIONS_NOT_FOUND";
    const INSUFFICIENT_INVENTORY = "INSUFFICIENT_INVENTORY";
    const TRANSIENT_ERROR = "TRANSIENT_ERROR";
    const INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS";
    const PURCHASE_TYPE_NOT_SUPPORTED = "PURCHASE_TYPE_NOT_SUPPORTED";
    const PAYPAL_ERROR_GENERAL = "PAYPAL_ERROR_GENERAL";
    const CARD_NUMBER_INCORRECT = "CARD_NUMBER_INCORRECT";
    const FRAUD_SUSPECTED = "FRAUD_SUSPECTED";
    const NON_TEST_ORDER_LIMIT_REACHED = "NON_TEST_ORDER_LIMIT_REACHED";
    const FREE_GIFT_CARD_NOT_ALLOWED = "FREE_GIFT_CARD_NOT_ALLOWED";
    const PAYMENT_METHOD_NOT_SPECIFIED = "PAYMENT_METHOD_NOT_SPECIFIED";
    const INVALID_BILLING_ADDRESS = "INVALID_BILLING_ADDRESS";
    const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";
    const AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED";
    const CALL_ISSUER = "CALL_ISSUER";
    const CARD_DECLINED = "CARD_DECLINED";
    const CONFIRMATION_REJECTED = "CONFIRMATION_REJECTED";
    const DO_NOT_HONOR = "DO_NOT_HONOR";
    const MERCHANT_RULE = "MERCHANT_RULE";
    const OFF_SESSION_REJECTED = "OFF_SESSION_REJECTED";
    const RETRY_DECLINED = "RETRY_DECLINED";
    const TRANSACTION_LIMIT_EXCEEDED = "TRANSACTION_LIMIT_EXCEEDED";
    const INCORRECT_ZIP = "INCORRECT_ZIP";
    const INVALID_AMOUNT = "INVALID_AMOUNT";
    const INVALID_CURRENCY = "INVALID_CURRENCY";
    const INVALID_CVC = "INVALID_CVC";
    const INVALID_NUMBER = "INVALID_NUMBER";
    const PAYMENT_METHOD_UNSUPPORTED = "PAYMENT_METHOD_UNSUPPORTED";
    const INCORRECT_ADDRESS = "INCORRECT_ADDRESS";
    const INCORRECT_CVC = "INCORRECT_CVC";
    const INCORRECT_NUMBER = "INCORRECT_NUMBER";
    const INCORRECT_PIN = "INCORRECT_PIN";
    const EXPIRED_CARD = "EXPIRED_CARD";
    const INVALID_EXPIRY_DATE = "INVALID_EXPIRY_DATE";
    const EXPIRED_BUYER_ACTION = "EXPIRED_BUYER_ACTION";
    const PROCESSING_ERROR = "PROCESSING_ERROR";
    const PAYMENT_PROVIDER_ERROR = "PAYMENT_PROVIDER_ERROR";
    const GENERIC_ERROR = "GENERIC_ERROR";
    const CANCELLED_PAYMENT = "CANCELLED_PAYMENT";
    const INVALID_PURCHASE_TYPE = "INVALID_PURCHASE_TYPE";
    const INVALID_REQUEST = "INVALID_REQUEST";
}
