<?php

namespace Fo3nix\ShopifyGraphQL\ShopifyAdmin202610;

use GraphQL\SchemaObject\EnumObject;

class ShopifySubscriptionContractCalculationDiagnosticCodeEnumObject extends EnumObject
{
    const INVALID = "INVALID";
    const MERCHANDISE_NOT_FOUND = "MERCHANDISE_NOT_FOUND";
    const DELIVERY_ADDRESS_INVALID = "DELIVERY_ADDRESS_INVALID";
    const CURRENCY_NOT_SUPPORTED = "CURRENCY_NOT_SUPPORTED";
    const DELIVERY_NO_LOCATION_SHIPS_TO_ADDRESS = "DELIVERY_NO_LOCATION_SHIPS_TO_ADDRESS";
    const DELIVERY_PICKUP_LOCATION_UNAVAILABLE = "DELIVERY_PICKUP_LOCATION_UNAVAILABLE";
    const PAYMENT_METHOD_NOT_FOUND = "PAYMENT_METHOD_NOT_FOUND";
    const CUSTOM_VALIDATION = "CUSTOM_VALIDATION";
    const DELIVERY_METHOD_REQUIRED = "DELIVERY_METHOD_REQUIRED";
    const DELIVERY_METHOD_UNUSED = "DELIVERY_METHOD_UNUSED";
    const CUSTOMER_CONTACT_METHOD_REQUIRED = "CUSTOMER_CONTACT_METHOD_REQUIRED";
    const BUNDLE_REQUIRES_MERCHANDISE_CUSTOMIZATIONS = "BUNDLE_REQUIRES_MERCHANDISE_CUSTOMIZATIONS";
    const MERCHANDISE_GIFT_CARD_INVALID = "MERCHANDISE_GIFT_CARD_INVALID";
    const DISCOUNT_CODE_NOT_APPLIED = "DISCOUNT_CODE_NOT_APPLIED";
    const CALCULATION_TIMEOUT = "CALCULATION_TIMEOUT";
    const LINE_PRICE_ADJUSTED_FOR_FULFILLMENTS = "LINE_PRICE_ADJUSTED_FOR_FULFILLMENTS";
    const PROCESSING_ERROR = "PROCESSING_ERROR";
}
