<?php

namespace Fo3nix\ShopifyGraphQL\ShopifyAdmin202607;

use GraphQL\SchemaObject\EnumObject;

class ShopifyShopifyqlDynamicColumnTypeEnumObject extends EnumObject
{
    const UNSPECIFIED = "UNSPECIFIED";
    const TOTALS = "TOTALS";
    const COMPARISON = "COMPARISON";
    const PERCENT_CHANGE = "PERCENT_CHANGE";
    const COMPARISON_TOTALS = "COMPARISON_TOTALS";
    const BENCHMARKS = "BENCHMARKS";
    const BENCHMARK_TOTALS = "BENCHMARK_TOTALS";
    const CUMULATIVE = "CUMULATIVE";
    const COMPARISON_CUMULATIVE = "COMPARISON_CUMULATIVE";
    const ATTRIBUTION = "ATTRIBUTION";
    const ATTRIBUTION_TOTALS = "ATTRIBUTION_TOTALS";
    const ATTRIBUTION_COMPARISON = "ATTRIBUTION_COMPARISON";
    const ATTRIBUTION_PERCENT_CHANGE = "ATTRIBUTION_PERCENT_CHANGE";
    const ATTRIBUTION_COMPARISON_TOTALS = "ATTRIBUTION_COMPARISON_TOTALS";
    const ATTRIBUTION_CUMULATIVE = "ATTRIBUTION_CUMULATIVE";
    const ATTRIBUTION_COMPARISON_CUMULATIVE = "ATTRIBUTION_COMPARISON_CUMULATIVE";
    const ROLLOUT_RESULTS = "ROLLOUT_RESULTS";
}
