<?php

namespace Fo3nix\ShopifyGraphQL\ShopifyAdmin202607;

use GraphQL\SchemaObject\EnumObject;

class ShopifyOrderTransactionErrorCodeEnumObject extends EnumObject
{
    const INCORRECT_NUMBER = "INCORRECT_NUMBER";
    const INVALID_NUMBER = "INVALID_NUMBER";
    const INVALID_EXPIRY_DATE = "INVALID_EXPIRY_DATE";
    const INVALID_CVC = "INVALID_CVC";
    const EXPIRED_CARD = "EXPIRED_CARD";
    const INCORRECT_CVC = "INCORRECT_CVC";
    const INCORRECT_ZIP = "INCORRECT_ZIP";
    const INCORRECT_ADDRESS = "INCORRECT_ADDRESS";
    const INCORRECT_PIN = "INCORRECT_PIN";
    const CARD_DECLINED = "CARD_DECLINED";
    const PROCESSING_ERROR = "PROCESSING_ERROR";
    const CALL_ISSUER = "CALL_ISSUER";
    const PICK_UP_CARD = "PICK_UP_CARD";
    const CONFIG_ERROR = "CONFIG_ERROR";
    const TEST_MODE_LIVE_CARD = "TEST_MODE_LIVE_CARD";
    const UNSUPPORTED_FEATURE = "UNSUPPORTED_FEATURE";
    const GENERIC_ERROR = "GENERIC_ERROR";
    const INVALID_COUNTRY = "INVALID_COUNTRY";
    const INVALID_AMOUNT = "INVALID_AMOUNT";
    const PAYMENT_METHOD_UNAVAILABLE = "PAYMENT_METHOD_UNAVAILABLE";
    const AMAZON_PAYMENTS_INVALID_PAYMENT_METHOD = "AMAZON_PAYMENTS_INVALID_PAYMENT_METHOD";
    const AMAZON_PAYMENTS_MAX_AMOUNT_CHARGED = "AMAZON_PAYMENTS_MAX_AMOUNT_CHARGED";
    const AMAZON_PAYMENTS_MAX_AMOUNT_REFUNDED = "AMAZON_PAYMENTS_MAX_AMOUNT_REFUNDED";
    const AMAZON_PAYMENTS_MAX_AUTHORIZATIONS_CAPTURED = "AMAZON_PAYMENTS_MAX_AUTHORIZATIONS_CAPTURED";
    const AMAZON_PAYMENTS_MAX_REFUNDS_PROCESSED = "AMAZON_PAYMENTS_MAX_REFUNDS_PROCESSED";
    const AMAZON_PAYMENTS_ORDER_REFERENCE_CANCELED = "AMAZON_PAYMENTS_ORDER_REFERENCE_CANCELED";
    const AMAZON_PAYMENTS_STALE = "AMAZON_PAYMENTS_STALE";
    const AMOUNT_TOO_LARGE = "AMOUNT_TOO_LARGE";
    const AMOUNT_TOO_SMALL = "AMOUNT_TOO_SMALL";
    const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";
    const AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED";
    const CANCELLED_PAYMENT = "CANCELLED_PAYMENT";
    const CARD_TESTING = "CARD_TESTING";
    const DO_NOT_HONOR = "DO_NOT_HONOR";
    const FRAUD_SUSPECTED = "FRAUD_SUSPECTED";
    const INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS";
    const INVALID_CURRENCY = "INVALID_CURRENCY";
    const INVALID_PAYMENT_METHOD = "INVALID_PAYMENT_METHOD";
    const INVALID_PURCHASE_TYPE = "INVALID_PURCHASE_TYPE";
    const MERCHANT_ACCOUNT_ERROR = "MERCHANT_ACCOUNT_ERROR";
    const MERCHANT_RULE = "MERCHANT_RULE";
    const INSTRUMENT_DECLINED = "INSTRUMENT_DECLINED";
    const PAYMENT_METHOD_UNSUPPORTED = "PAYMENT_METHOD_UNSUPPORTED";
    const PAYMENT_PROVIDER_ERROR = "PAYMENT_PROVIDER_ERROR";
    const RETRY_DECLINED = "RETRY_DECLINED";
    const TRANSACTION_LIMIT_EXCEEDED = "TRANSACTION_LIMIT_EXCEEDED";
    const AUTHORIZATION_EXPIRED = "AUTHORIZATION_EXPIRED";
}
